/**
 * PDF Export utility using the browser's native print API.
 * Generates formatted clinical reports for Patient Summaries, Handovers, and Executive Reports.
 */

interface PDFExportOptions {
  title: string
  content: string
  patientId?: string
  riskScore?: number
  timestamp?: string
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
    .replace(/\n/g, '<br>')
}

export function exportToPDF(options: PDFExportOptions): void {
  const { title, content, patientId, riskScore, timestamp = new Date().toLocaleString() } = options

  const riskBadge = riskScore !== undefined
    ? riskScore > 0.8
      ? `<span class="badge badge-critical">CRITICAL ${(riskScore * 100).toFixed(1)}%</span>`
      : riskScore > 0.5
        ? `<span class="badge badge-high">HIGH ${(riskScore * 100).toFixed(1)}%</span>`
        : `<span class="badge badge-normal">LOW ${(riskScore * 100).toFixed(1)}%</span>`
    : ''

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${title} — PREMONITION</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; padding: 40px; line-height: 1.7; font-size: 14px; }
        .header { border-bottom: 3px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { font-size: 22px; color: #4f46e5; font-weight: 800; margin-bottom: 8px; }
        .header .meta { display: flex; flex-wrap: wrap; gap: 16px; font-size: 12px; color: #64748b; }
        .meta-item strong { color: #1e293b; }
        .badge { display: inline-block; padding: 3px 12px; border-radius: 999px; font-size: 11px; font-weight: 700; margin-left: 8px; }
        .badge-critical { background: #fee2e2; color: #dc2626; border: 1px solid #fca5a5; }
        .badge-high { background: #ffedd5; color: #ea580c; border: 1px solid #fdba74; }
        .badge-normal { background: #dcfce7; color: #16a34a; border: 1px solid #86efac; }
        h2 { color: #4f46e5; font-size: 16px; margin: 24px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
        h3 { color: #334155; font-size: 14px; margin: 16px 0 6px; }
        p, li { color: #475569; margin-bottom: 6px; }
        ul { padding-left: 20px; margin-bottom: 12px; }
        strong { color: #1e293b; }
        .content { line-height: 1.8; }
        .watermark { position: fixed; bottom: 20px; right: 20px; font-size: 10px; color: #cbd5e1; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; display: flex; justify-content: space-between; }
        @media print { body { padding: 20px; } .watermark { display: none; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🏥 PREMONITION AI — ${title} ${riskBadge}</h1>
        <div class="meta">
          ${patientId ? `<div class="meta-item"><strong>Patient ID:</strong> ${patientId}</div>` : ''}
          ${riskScore !== undefined ? `<div class="meta-item"><strong>Sepsis Risk:</strong> ${(riskScore * 100).toFixed(1)}%</div>` : ''}
          <div class="meta-item"><strong>Generated:</strong> ${timestamp}</div>
          <div class="meta-item"><strong>System:</strong> PREMONITION Agentic AI Platform v2.0</div>
          <div class="meta-item"><strong>Classification:</strong> CONFIDENTIAL — FOR CLINICAL USE ONLY</div>
        </div>
      </div>
      <div class="content">${markdownToHtml(content)}</div>
      <div class="footer">
        <span>Generated by PREMONITION AI · ${timestamp}</span>
        <span>CONFIDENTIAL — FOR CLINICAL USE ONLY</span>
      </div>
    </body>
    </html>
  `

  const win = window.open('', '_blank', 'width=900,height=1100')
  if (win) {
    win.document.write(html)
    win.document.close()
    setTimeout(() => {
      win.focus()
      win.print()
    }, 600)
  }
}

export function exportPatientSummaryPDF(patientId: string, summary: string, riskScore?: number): void {
  exportToPDF({
    title: `Patient Summary — ${patientId}`,
    content: summary,
    patientId,
    riskScore,
  })
}

export function exportHandoverPDF(content: string): void {
  exportToPDF({
    title: 'ICU Shift Handover Report',
    content,
  })
}

export function exportExecutiveReportPDF(content: string): void {
  exportToPDF({
    title: 'Executive Clinical Intelligence Report',
    content,
  })
}
