apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: premonition-ingress
  namespace: premonition
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - api.premonition.health
      secretName: premonition-tls
  rules:
    - host: api.premonition.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: premonition-api
                port:
                  number: 80
