apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premonition-models-pvc
  namespace: premonition
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: premonition-logs-pvc
  namespace: premonition
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
