apiVersion: v1
kind: Secret
metadata:
  name: {{ include "premonition.fullname" . }}-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | default "CHANGE-ME" | quote }}
  api-key: {{ .Values.secrets.apiKey | default "" | quote }}
