@echo off
echo Starting Final Verification...
cd frontend
echo Building frontend...
call npm run build
if %errorlevel% neq 0 exit /b %errorlevel%
cd ..
echo Running Tests...
call npm test --prefix frontend --passWithNoTests
echo Running Pytest...
call pytest
echo Verification Complete.
